# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cdcc6c28e1ded72830956a3ec9c3b3f0327ed2b6f8097533b65105c4f8eeafc31119eef6dc7dc6fcb477426c977eacc1884313c58c86801874b866efe1f32f53

test:
  secret_key_base: bd428c5a948d0ab2a759345877700a968cf09be5939a20dcf4a42b1e482dd2f6f1c566e4c1528bf529ea2568fcbf9c3a8ce3edbb43451d44d2acc71f8e32ab36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
